name: Push to Azure Container Registry
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker Frontend image to Azure Container Registry
        run: |
            docker tag pizzafrontend:latest natnacr.azurecr.io/pizzafrontend:v1
            docker push natnacr.azurecr.io/pizzafrontend:v1         

      - name: Push Docker Backend image to Azure Container Registry
        run: |
            docker tag pizzabackend:latest natnacr.azurecr.io/pizzabackend:v1
            docker push natnacr.azurecr.io/pizzabackend:v1

